version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017 Preview
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
  - git config --global core.autocrlf true
  - ps: $Env:LABEL = "ci" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - cd src/
  - dotnet --version
  - dotnet restore
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build Staudt.Engineering.LidaRx --no-dependencies -c %CONFIGURATION% --version-suffix %LABEL%
- dotnet build Staudt.Engineering.LidaRx.Drivers.R2000 --no-dependencies -c %CONFIGURATION% --version-suffix %LABEL%
- dotnet build Staudt.Engineering.LidaRx.Drivers.Sweep --no-dependencies -c %CONFIGURATION% --version-suffix %LABEL%
after_build:
- dotnet pack Staudt.Engineering.LidaRx --no-dependencies -c %CONFIGURATION% --version-suffix %LABEL%
- dotnet pack Staudt.Engineering.LidaRx.Drivers.R2000 --no-dependencies -c %CONFIGURATION% --version-suffix %LABEL%
- dotnet pack Staudt.Engineering.LidaRx.Drivers.Sweep --no-dependencies -c %CONFIGURATION% --version-suffix %LABEL%
artifacts:
- path: '**\Staudt.Engineering.LidaRx*.nupkg' # find all NuGet packages recursively
deploy:
- provider: NuGet
  api_key:
    secure: vPlXoLcRaQ3ewpPTbaLP4AmmbWpNGlAKC32Ml2sfqAHxAZhlAaZrYKYWcHO08SWS
  artifact: /.*\.nupkg/
  on:
    branch: master