version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017 Preview
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
  - git config --global core.autocrlf true
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - cd src/
  - dotnet --version
  - dotnet restore
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build -c %CONFIGURATION% --version-suffix %LABEL%
after_build:
- dotnet pack -c %CONFIGURATION% --version-suffix %LABEL%
artifacts:
- path: '**\Staudt.Engineering.LidaRx*.nupkg' # find all NuGet packages recursively